version: '3'

services:
  mooc_mysql:
    container_name: codely-infra_modeling_inheritance_mapping-performance
    image: mariadb:11.2.2
    ports:
      - "3336:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mooc.sql:/data/mooc.sql
      - ./fill_tables.sh:/data/mooc.sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent"]
      interval: 2s
      timeout: 10s
      retries: 10
    command: ["--default-authentication-plugin=mysql_native_password"]
